version: 2.1

restore-workspace: &restore-workspace
  attach_workspace:
    at: ~/

branch-filter: &branch-filter
  branches:
    only: [master]

executors:
  node:
    docker:
      - image: circleci/node:12.14.0
    working_directory: ~/quotatious

jobs:
  checkout-install-dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: quotatious-node-modules-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: quotatious-node-modules-{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: ~/
          paths: quotatious

  yarn-build:
    executor: node
    steps:
      - *restore-workspace
      - run: yarn build
      - persist_to_workspace:
          root: ~/
          paths: quotatious/.next

workflows:
  version: 2

  build-deploy:
    jobs:
      - checkout-install-dependencies
      - yarn-build:
          name: build
          requires: [checkout-install-dependencies]
